config/routes.rb
Ohmyroots::Application.routes.draw do

  resources :credits

  devise_for :admins
match 'faqs/privacy', :to => 'faqs#privacy'
  resources :faqs

  root to: "movies#dashboard"
  match 'movies/dashboard', :to => 'movies#dashboard'
  match 'movies/upload', :to => 'movies#upload'
  match 'reviews/show', :to => 'reviews#show'
  match 'movies/suggest', :to => 'movies#suggest'

  resources :reviews
  resources :movies
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  devise_for :users, :controllers => { :registrations => "registrations" }
  

  match 'show/:id', :to => 'movies#show'
  

   match ':controller(/:action(/:id))(.:format)'
end

app/models/faq.rb
class Faq < ActiveRecord::Base
  attr_accessible :answer, :question
end

app/controllers/faqs_controller.rb
class FaqsController < ApplicationController
  before_filter :authenticate_admin!, :only => [:new, :edit,:destroy], :except => [:index,:privacy]
  # GET /faqs
  # GET /faqs.json
  def index
    @faqs = Faq.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @faqs }
    end
  end

  # GET /faqs/1
  # GET /faqs/1.json
  def show
    @faq = Faq.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @faq }
    end
  end

  # GET /faqs/new
  # GET /faqs/new.json
  def new
    @faq = Faq.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @faq }
    end
  end

  # GET /faqs/1/edit
  def edit
    @faq = Faq.find(params[:id])
  end

  # POST /faqs
  # POST /faqs.json
  def create
    @faq = Faq.new(params[:faq])

    respond_to do |format|
      if @faq.save
        format.html { redirect_to @faq, notice: 'Faq was successfully created.' }
        format.json { render json: @faq, status: :created, location: @faq }
      else
        format.html { render action: "new" }
        format.json { render json: @faq.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /faqs/1
  # PUT /faqs/1.json
  def update
    @faq = Faq.find(params[:id])

    respond_to do |format|
      if @faq.update_attributes(params[:faq])
        format.html { redirect_to @faq, notice: 'Faq was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @faq.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /faqs/1
  # DELETE /faqs/1.json
  def destroy
    @faq = Faq.find(params[:id])
    @faq.destroy

    respond_to do |format|
      format.html { redirect_to faqs_url }
      format.json { head :no_content }
    end
  end

  def privacy
  end
  
end

app/helpers/faqs_helper.rb
module FaqsHelper
end

app/views/faqs/_form.html.erb
<%= form_for(@faq) do |f| %>
  <% if @faq.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@faq.errors.count, "error") %> prohibited this faq from being saved:</h2>

      <ul>
      <% @faq.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :question %><br />
    <%= f.text_area :question %>
  </div>
  <div class="field">
    <%= f.label :answer %><br />
    <%= f.text_area :answer %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/faqs/edit.html.erb
<h1>Editing faq</h1>

<%= render 'form' %>

<%= link_to 'Show', @faq %> |
<%= link_to 'Back', faqs_path %>

app/views/faqs/index.html.erb
<%
  title 'FAQs'

%>
<h3 xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">FAQ</h3>
<% @faqs.each do |faq| %>

<table>
  <tr>
    <td><b><%= faq.question %></b></td>
  </tr>
  <tr>
    <td><%= faq.answer %></td>
  </tr>
    <!--td><%= link_to 'Show', faq %></td>
    <td><%= link_to 'Edit', edit_faq_path(faq) %></td>
    <td><%= link_to 'Destroy', faq, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr-->
</table>
<div id="push">

</div>
<% end %>
<br />

<!--<%= link_to 'New Faq', new_faq_path %>-->

app/views/faqs/new.html.erb
<h1>New faq</h1>

<%= render 'form' %>

<%= link_to 'Back', faqs_path %>

app/views/faqs/privacy.html.erb
<%
  title 'Privacy Policy'
%>

This Privacy Policy governs the manner in which Movie Pulse collects, uses, maintains and discloses information collected from users (each, a "User") of the <a href="moviepulse.com.au">moviepulse.com.au</a> website ("Site"). This privacy policy applies to the Site and all products and services offered by Movie Pulse.<br><br>

<b>Personal identification information</b><br><br>

We may collect personal identification information from Users in a variety of ways, including, but not limited to, when Users visit our site, register on the site, and in connection with other activities, services, features or resources we make available on our Site. Users may be asked for, as appropriate, name, email address, mailing address. Users may, however, visit our Site anonymously. We will collect personal identification information from Users only if they voluntarily submit such information to us. Users can always refuse to supply personally identification information, except that it may prevent them from engaging in certain Site related activities.<br><br>

<b>Non-personal identification information</b><br><br>

We may collect non-personal identification information about Users whenever they interact with our Site. Non-personal identification information may include the browser name, the type of computer and technical information about Users means of connection to our Site, such as the operating system and the Internet service providers utilized and other similar information.<br><br>

<b>Web browser cookies</b><br><br>

Our Site may use "cookies" to enhance User experience. User's web browser places cookies on their hard drive for record-keeping purposes and sometimes to track information about them. User may choose to set their web browser to refuse cookies, or to alert you when cookies are being sent. If they do so, note that some parts of the Site may not function properly.<br><br>

<b>How we use collected information</b><br><br>

Movie Pulse may collect and use Users personal information for the following purposes:<br>
<ul>
<li><i>- To personalize user experience</i><br>
	We may use information in the aggregate to understand how our Users as a group use the services and resources provided on our Site.</li>
<li><i>- To process payments</i><br>
	We may use the information Users provide about themselves when placing an order only to provide service to that order. We do not share this information with outside parties except to the extent necessary to provide the service.</li>
<li><i>- To send periodic emails</i><br>
If User decides to opt-in to our mailing list, they will receive emails that may include company news, updates, related product or service information, etc. If at any time the User would like to unsubscribe from receiving future emails, we include detailed unsubscribe instructions at the bottom of each email.</li>
</ul>
<b>How we protect your information</b><br><br>

We adopt appropriate data collection, storage and processing practices and security measures to protect against unauthorized access, alteration, disclosure or destruction of your personal information, username, password, transaction information and data stored on our Site.<br><br>

Sensitive and private data exchange between the Site and its Users happens over a SSL secured communication channel and is encrypted and protected with digital signatures.<br><br>

<b>Sharing your personal information</b><br><br>

We do not sell, trade, or rent Users personal identification information to others. We may share generic aggregated demographic information not linked to any personal identification information regarding visitors and users with our business partners, trusted affiliates and advertisers for the purposes outlined above.<br><br>

<b>Third party websites</b><br><br>

Users may find advertising or other content on our Site that link to the sites and services of our partners, suppliers, advertisers, sponsors, licensors and other third parties. We do not control the content or links that appear on these sites and are not responsible for the practices employed by websites linked to or from our Site. In addition, these sites or services, including their content and links, may be constantly changing. These sites and services may have their own privacy policies and customer service policies. Browsing and interaction on any other website, including websites which have a link to our Site, is subject to that website's own terms and policies.<br><br>

<b>Advertising</b><br><br>

Ads appearing on our site may be delivered to Users by advertising partners, who may set cookies. These cookies allow the ad server to recognize your computer each time they send you an online advertisement to compile non personal identification information about you or others who use your computer. This information allows ad networks to, among other things, deliver targeted advertisements that they believe will be of most interest to you. This privacy policy does not cover the use of cookies by any advertisers.<br><br>

<b>Google Adsense</b><br><br>

Some of the ads may be served by Google. Google's use of the DART cookie enables it to serve ads to Users based on their visit to our Site and other sites on the Internet. DART uses "non personally identifiable information" and does NOT track personal information about you, such as your name, email address, physical address, etc. You may opt out of the use of the DART cookie by visiting the Google ad and content network privacy policy at <a href="http://www.google.com/privacy_ads.html">http://www.google.com/privacy_ads.html</a><br><br>

<b>Compliance with children's online privacy protection act</b><br><br>

Protecting the privacy of the very young is especially important. For that reason, we never collect or maintain information at our Site from those we actually know are under 13, and no part of our website is structured to attract anyone under 13.<br><br>

<b>Changes to this privacy policy</b><br><br>

Movie Pulse has the discretion to update this privacy policy at any time. When we do, we will revise the updated date at the bottom of this page. We encourage Users to frequently check this page for any changes to stay informed about how we are helping to protect the personal information we collect. You acknowledge and agree that it is your responsibility to review this privacy policy periodically and become aware of modifications.<br><br>

<b>Your acceptance of these terms</b><br><br>

By using this Site, you signify your acceptance of this policy. If you do not agree to this policy, please do not use our Site. Your continued use of the Site following the posting of changes to this policy will be deemed your acceptance of those changes.<br><br>

<b>Contacting us</b><br><br>

If you have any questions about this Privacy Policy, the practices of this site, or your dealings with this site, please contact us at:<br>
<a href="moviepulse.com.au">Movie Pulse</a><br>
<a href="moviepulse.com.au">moviepulse.com.au</a><br>
rails4sandeep@gmail.com<br>
<br>
This document was last updated on August 28, 2013<br><br>

<div style="font-size:10px;color:gray;">Privacy policy created by <a style="font-size:10px;color:gray;text-decoration:none;cursor:default;" href="http://www.generateprivacypolicy.com" target="_blank">Generate Privacy Policy</a></div>

app/views/faqs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Question:</b>
  <%= @faq.question %>
</p>

<p>
  <b>Answer:</b>
  <%= @faq.answer %>
</p>


<%= link_to 'Edit', edit_faq_path(@faq) %> |
<%= link_to 'Back', faqs_path %>