config/routes.rb
Ohmyroots::Application.routes.draw do

  resources :credits

  devise_for :admins
match 'faqs/privacy', :to => 'faqs#privacy'
  resources :faqs

  root to: "movies#dashboard"
  match 'movies/dashboard', :to => 'movies#dashboard'
  match 'movies/upload', :to => 'movies#upload'
  match 'reviews/show', :to => 'reviews#show'
  match 'movies/suggest', :to => 'movies#suggest'

  resources :reviews
  resources :movies
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  devise_for :users, :controllers => { :registrations => "registrations" }
  

  match 'show/:id', :to => 'movies#show'
  

   match ':controller(/:action(/:id))(.:format)'
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_filter :authenticate_admin!, :only => [:new, :create], :except => [:index,:show,:movie,:dashboard,:create_from_tmdb,:suggest,:suggest_movies]
  include MoviesHelper

  def index
    @tmdb_movie_results=[]
    @search=Movie.search(params[:q])
    if params[:q].nil? then
      @search=Movie.search(params[:q])
      @movie_results=[]
    else
      @search=Movie.search(params[:q])
      @movie_results=@search.result
    end
    if params[:q].nil? || params[:q]['name_cont'].empty?
      @tmdb_movie_results=[]
    else   
      @tmdb_movie_results=matching_movie_results(params[:q]['name_cont'])
    end
    @movies=Kaminari.paginate_array(@movie_results).page(params[:page]).per(5)
    @tmdb_movies=Kaminari.paginate_array(@tmdb_movie_results).page(params[:page]).per(5)
  end

  def show
    @users=Array.new
    @ratings=Array.new
    @movie=Movie.find(params[:id])
    @reviews=Review.reviews_for_movie(params[:id])
    @reviews.each do |review|
      @users << User.find(review.user_id)
      @ratings << review.rating
    end
    @average_movie_rating=(@ratings.sum)/(@ratings.count) unless @ratings.empty?

    begin
      data_table = GoogleVisualr::DataTable.new
      data_table.new_column('string'  , 'Label')
      data_table.new_column('number'  , 'Value')
      data_table.add_rows(1)
      data_table.set_cell(0, 0, 'Rating' )
      if @ratings.empty?
        data_table.set_cell(0, 1, @movie.movie_average_rating)
        opts   = { :width => 400,:height => 120,:majorTicks => 10,:minorTicks => 5,:max => 10,:yellowFrom => 0, :yellowTo => @movie.movie_average_rating }
      else
        data_table.set_cell(0, 1, @movie_average_rating)    
        opts   = { :width => 400,:height => 120,:majorTicks => 10,:minorTicks => 5,:max => 10,:yellowFrom => 0, :yellowTo => @movie_average_rating }
      end  
      
      
      @chart = GoogleVisualr::Interactive::Gauge.new(data_table, opts)
    end
  end

  def movie

    @users=Array.new
    @movie=Movie.find(:movie)
    @reviews=Review.reviews_for_movie(:movie)

    @reviews.each do |review|
      @users << User.find(review.user_id)
    end
  end

  def new
    @movie=Movie.new
  end

  def create
    @movie = Movie.new params[:movie]
      if gotcha_valid? && @movie.save
        flash[:notice] = 'Movie was successfully created.'
        redirect_to :action => "show", :id => @movie.id
      else
        render :action => "new"
      end
  end

  def create_from_tmdb
    if Movie.where(:tmdb_id => params[:id]).empty?
      @movie = Movie.new
      @movie.name=movie_title(params[:id])
      @movie.tmdb_id=params[:id]
      if @movie.save
        #flash[:notice] = 'Movie was successfully created.'
        redirect_to :action => "show", :id => @movie.id
      else
        render :action => "index"
      end
    else
      @movie=Movie.where(:tmdb_id => params[:id]).first
      redirect_to :action => "show", :id => @movie.id
    end  

  end

  def dashboard
    #@movies=Movie.movies_by_average_rating
    #@movies=Kaminari.paginate_array(Movie.movies_by_average_rating).page(params[:page]).per(10)
    #@movies_men=top_rated_by_sex('male')
    #@movies_women=top_rated_by_sex('female')
    #@movies_youth=top_rated_by_youth(40)
    #@current_movies=currently_talked_about
    #@movies_dampsquibs=damp_squibs
    @movies_now_playing=now_playing
    #@movies_now_playing_au=Movie.movies_now_playing_australia
    @movies_upcoming=upcoming
    @movies_popular=popular
    #@movies_tmdb_top_rated=tmdb_top_rated
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])
      if @movie.update_attributes(params[:movie])
        redirect_to @movie, notice: 'Movie was successfully updated.' 
      else
        render action: "edit"
      end
    
  end

  def import
    logger.debug("inside movies import--->#{params[:file].inspect}")
    require 'csv'
    @lines = []
    Movie.update_all("now_playing_au=0")
    uploaded_io=params[:file]
    File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'w') do |file|
        file.write(uploaded_io.read)
      end
    File.foreach(Rails.root.join('public', 'uploads', uploaded_io.original_filename)){|line| logger.debug line}
    lines=IO.readlines(Rails.root.join('public', 'uploads', uploaded_io.original_filename))
    lines.each{|l| logger.debug l}
      lines.each do |line|
      movie_id=line.split(',').first
      movie_name=line.split(',').last
      if Movie.where(:tmdb_id => movie_id).empty?
        @movie=Movie.new
        @movie.tmdb_id=movie_id
        @movie.name=movie_name
        @movie.now_playing_au=1
        @movie.save
      else
        @movie=Movie.where(:tmdb_id => movie_id).first
        @movie.now_playing_au=1
        @movie.save
      end
    end
    redirect_to action: "index", notice: 'Australia Movie Release Data Imported'
  end

  def upload
    
  end

  #def suggest

  #end

  def suggest
     @suggest_results=suggested_movie_results(params[:name]) unless params[:name].nil?
     @name = params[:name]
  end

end

app/helpers/movies_helper.rb
module MoviesHelper

	def top_rated_recent_releases
	    movies=Array.new
	    movie_hash=Hash.new(0)
	    reviews=Review.where(:rating => [4,5,6,7,8,9])
	    reviews.each do |review|
	      movies << Movie.find(review.movie_id) if Movie.find(review.movie_id).release.between?(Date.today-90,Date.today)
	    end

	    movies.each do |movie|
	    	movie_hash[movie] = movie_hash[movie] + 1
	    end
	    movie_hash.sort{|x,y| y[1] <=> x[1] }
	    movies=[]
	    movie_hash.each do |x,y|
	    	movies << x
	    end	
	    return movies
  end

  def top_rated_by_sex(sex)
	    movies=Array.new
	    reviews_men=Array.new
	    movie_hash=Hash.new(0)

	    reviews=Review.where(:rating => [4,5,6,7,8,9])
	    reviews.each do |review|
	    	reviews_men << review if (User.find(review.user_id)).sex==sex
	    end
	    reviews_men.each do |review|
	      movies << Movie.find(review.movie_id)
	    end

	    movies.each do |movie|
	    	movie_hash[movie] = movie_hash[movie] + 1
	    end
	    movie_hash.sort{|x,y| y[1] <=> x[1] }
	    movies=[]
	    movie_hash.each do |x,y|
	    	movies << x
	    end	
	    return movies
  end

  def top_rated_by_youth(age)
	    movies=Array.new
	    reviews_men=Array.new
	    movie_hash=Hash.new(0)

	    reviews=Review.where(:rating => [4,5,6,7,8,9])
	    reviews.each do |review|
	    	reviews_men << review if User.find(review.user_id).age.to_i.between?(20,age)
	    end
	    reviews_men.each do |review|
	      movies << Movie.find(review.movie_id)
	    end

	    movies.each do |movie|
	    	movie_hash[movie] = movie_hash[movie] + 1
	    end
	    movie_hash.sort{|x,y| y[1] <=> x[1] }
	    movies=[]
	    movie_hash.each do |x,y|
	    	movies << x
	    end	
	    return movies[0..4]

  end

  def currently_talked_about
		movies=Array.new
	    reviews_latest=Array.new
	    movie_hash=Hash.new(0)
	    reviews=Review.where(:rating => [4,5,6,7,8,9])
	    reviews.each do |review|
	    	reviews_latest << review if review.created_at.to_date==Date.today
	    end
	    reviews_latest.each do |review|
	      movies << Movie.find(review.movie_id)
	    end
	    movies.each do |movie|
	    	movie_hash[movie] = movie_hash[movie] + 1
	    end
	    movie_hash.sort{|x,y| y[1] <=> x[1] }
	    movies=[]
	    movie_hash.each do |x,y|
	    	movies << x
	    end
	    return movies[0..4]	
  end

  def damp_squibs
	    movies=Array.new
	    movie_hash=Hash.new(0)
	    reviews=Review.where(:rating => [1,2])
	    reviews.each do |review|
	      movies << Movie.find(review.movie_id)
	    end

	    movies.each do |movie|
	    	movie_hash[movie] = movie_hash[movie] + 1
	    end
	    movie_hash.sort{|x,y| y[1] <=> x[1] }
	    movies=[]
	    movie_hash.each do |x,y|
	    	movies << x
	    end	
	    return movies[0..4]
  end

  def now_playing
  	movies=Array.new
  	@now_playing=Tmdb::Movie.now_playing
  	@now_playing.each do |movie|
  		begin
	  		movie_hash=Hash.new
  			movie_hash[:name]=movie['original_title']
  			movie_hash[:tmdb_id]=movie['id']
  			movies << movie_hash
  		end unless movie.nil?
  	end
  	return movies
  end

  def upcoming
  	movies=Array.new
  	@upcoming=Tmdb::Movie.upcoming
  	@upcoming.each do |movie|
  		begin
	  		movie_hash=Hash.new
  			movie_hash[:name]=movie['original_title']
  			movie_hash[:tmdb_id]=movie['id']
  			movies << movie_hash
  		end unless movie.nil?
  	end
  	return movies
  end

  def popular
  	movies=Array.new
  	@popular=Tmdb::Movie.popular
  	@popular.each do |movie|
  		begin
	  		movie_hash=Hash.new
  			movie_hash[:name]=movie['original_title']
  			movie_hash[:tmdb_id]=movie['id']
  			movies << movie_hash
  		end unless movie.nil?
  	end
  	return movies
  end

  def tmdb_top_rated
  	movies=Array.new
  	@tmdb_top_rated=Tmdb::Movie.top_rated
  	@tmdb_top_rated.each do |movie|
  		begin
	  		movie_hash=Hash.new
  			movie_hash[:name]=movie['original_title']
  			movie_hash[:tmdb_id]=movie['id']
  			movies << movie_hash
  		end unless movie.nil?
  	end
  	return movies
  end

def movie_title(movie_id)
    Tmdb::Movie.detail(movie_id).original_title
  end

def matching_movie_results(movie_name)
  Tmdb::Movie.find(movie_name)
end

def poster_url_path(tmdb_id)
  configuration = Tmdb::Configuration.new
  if Tmdb::Movie.detail(tmdb_id).poster_path.nil?
    poster_path=''
  else
    poster_path=Tmdb::Movie.detail(tmdb_id).poster_path
  end  
    @poster_url=configuration.base_url+'w500'+poster_path
end

  def backdrop_url_path(tmdb_id)
    configuration = Tmdb::Configuration.new
    if Tmdb::Movie.detail(tmdb_id).backdrop_path.nil?
      backdrop_path=''
    else
      backdrop_path=Tmdb::Movie.detail(tmdb_id).backdrop_path
    end
    @poster_url=configuration.base_url+'original'+backdrop_path
  end

  def movie_tweets(movie_name,result_type)
    @tweets=[]
    $twitter_client.search(movie_name, :result_type => result_type,:lang => "en").take(50).each do |tweet|
      @tweets << tweet
    end
  end

end

app/views/movies/dashboard.erb
<style type="text/css">
    body {

        //background-image: url(<%= backdrop_url_path(@movies_now_playing.to_a.sample[:tmdb_id]) %>);
        //background-repeat: space;
        //background-position: 100%;
        //background-size: auto;
    }
</style>

<%
  title 'Dashboard: What Australia is watching'
%>

<table>
<caption><b>Now Playing</b></caption>
<% cache('movies_now_playing',:expires_in => 6.hours) do %>
<tr><td>
<div id="movies_now_playing" class="carousel slide" style="width: 400px; margin: 0 auto">
  <ol class="carousel-indicators">
    <li data-target="#movies_now_playing" data-slide-to="0" class="active"></li>
    <li data-target="#movies_now_playing" data-slide-to="1"></li>
    <li data-target="#movies_now_playing" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <% @movies_now_playing.each_with_index do |post,count| %>
      <% if count==0 %>
        <div class="active item"><%= link_to image_tag(poster_url_path(post[:tmdb_id])),controller: "movies", action: "create_from_tmdb", id: post[:tmdb_id] %></div>
      <% else %>
        <div class="item"><%= link_to image_tag(poster_url_path(post[:tmdb_id])),controller: "movies", action: "create_from_tmdb", id: post[:tmdb_id] %></div>
      <% end %>
    <% end %>
  </div>
  <a class="carousel-control left" href="#movies_now_playing" data-slide="prev">&lsaquo;</a>
  <a class="carousel-control right" href="#movies_now_playing" data-slide="next">&rsaquo;</a>
</div>
</td></tr>
<% end %>
</table>

<table>
<caption><b>Coming Soon</b></caption>
<% cache('movies_upcoming',:expires_in => 6.hours) do %>
<tr><td>
<div id="movies_upcoming" class="carousel slide" style="width: 400px; margin: 0 auto">
  <ol class="carousel-indicators">
    <li data-target="#movies_upcoming" data-slide-to="0" class="active"></li>
    <li data-target="#movies_upcoming" data-slide-to="1"></li>
    <li data-target="#movies_upcoming" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <% @movies_upcoming.each_with_index do |post,count| %>
      <% if count==0 %>
        <div class="active item"><%= link_to image_tag(poster_url_path(post[:tmdb_id])),controller: "movies", action: "create_from_tmdb", id: post[:tmdb_id] %></div>
      <% else %>
        <div class="item"><%= link_to image_tag(poster_url_path(post[:tmdb_id])),controller: "movies", action: "create_from_tmdb", id: post[:tmdb_id] %></div>
      <% end %>
    <% end %>
  </div>
  <a class="carousel-control left" href="#movies_upcoming" data-slide="prev">&lsaquo;</a>
  <a class="carousel-control right" href="#movies_upcoming" data-slide="next">&rsaquo;</a>
</div>
</td></tr>
<% end %>
</table>

<table>
<caption><b>Most Searched</b></caption>
<% cache('movies_popular',:expires_in => 6.hours) do %>
<tr><td>
<div id="movies_popular" class="carousel slide" style="width: 400px; margin: 0 auto">
  <ol class="carousel-indicators">
    <li data-target="#movies_popular" data-slide-to="0" class="active"></li>
    <li data-target="#movies_popular" data-slide-to="1"></li>
    <li data-target="#movies_popular" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <% @movies_popular.each_with_index do |post,count| %>
      <% if count==0 %>
        <div class="active item"><%= link_to image_tag(poster_url_path(post[:tmdb_id])),controller: "movies", action: "create_from_tmdb", id: post[:tmdb_id] %></div>
      <% else %>
        <div class="item"><%= link_to image_tag(poster_url_path(post[:tmdb_id])),controller: "movies", action: "create_from_tmdb", id: post[:tmdb_id] %></div>
      <% end %>
    <% end %>
  </div>
  <a class="carousel-control left" href="#movies_popular" data-slide="prev">&lsaquo;</a>
  <a class="carousel-control right" href="#movies_popular" data-slide="next">&rsaquo;</a>
</div>
</td></tr>
<% end %>
</table>

app/views/movies/edit.html.erb
<%= form_for(@movie) do |f| %>
<table>
	<tr>
		<td>
		  <%= f.label :name, "Name" %>
  		  <%= f.text_field :name %>
		</td>
	</tr>
	<tr>
		<td><%= f.check_box :now_playing_au %>
		<%= f.label :now_playing_au, "Now Playing Australia" %></td>
	</tr>
	<tr>
		<td><%= f.submit "Save", :disable_with => 'Saving...' %></td>
	</tr>
</table>

<% end %>

app/views/movies/index.erb
<%
  title 'Search: search a movie'
%>

<div class="span6">  
<div class="navbar-search">
  <%= search_form_for @search do |f| %>
  <table>
    <tr>
      <td>
        <%= f.text_field :name_cont,:class => "search-query" %>
        <%= f.submit "Search Movies",:class => "btn" %>
      </td>
    </tr>
    <tr>
      <td>
        <strong>
          or see what Australia is <%= link_to "liking", controller: "movies", action: "dashboard" %>
        </strong>
      </td>
    </tr>
  </table>

<% end %>

<!--   <% if !@movie_results.empty? %>
  
  <table class="table table-bordered table-condensed table-striped">
    <caption><b>From movie pulse database</b></caption>
  <tr>
    <th><%= sort_link @search,:name, "Name"  %></th>
  </tr>
  <% @movies.each do |post| %>
      <tr>
        <td><%= link_to "#{post.name}", post %></td>
        <% if admin_signed_in? %>
        <td><%= link_to 'Edit', edit_movie_path(post),:class => "btn btn-inverse" %></td>
        <% end %>
      </tr>
  <% end %>
  </table>
  <%= paginate @movies %>
  </div>
<% end %>
 -->
</div>


<% if !@tmdb_movie_results.empty? %>
<div class="span6">
  <table class="table table-bordered table-condensed table-striped">
    <caption><b>Did you mean</b></caption>
  <tr>
    <th><%= sort_link @search,:name, "Name"  %></th>
  </tr>
  <% @tmdb_movies.each do |post| %>
      <tr>
        <td>
          <%= link_to "#{post.title}",controller: "movies", action: "create_from_tmdb",id: post.id %>
        </td>
      </tr>
  <% end %>
  </table>
  <% end %>
  <%= paginate @tmdb_movies %>
  </div>
</div>

app/views/movies/new.erb
<h3>Add Movie</h3>
<div class="form-horizontal">
<table>

<%= form_for @movie do |f| %>
<%= render "shared/error_messages",:target => @movie %>
<div>
	<%= f.label :name, "Name" %>
	<%= f.text_field :name %>
</div>
<div>
<%= f.label :release, "Release" %>
<%= f.date_select :release %>
</div>
<div>
<%= f.label :actors, "Actors" %>
<%= f.text_field :actors %>
</div>
<div>
<%= f.label :director, "Director" %>
<%= f.text_field :director %>
</div>
<div>
<%= f.label :music, "Music" %>
<%= f.text_field :music %>
</div>
<div>
<%= f.label :description, "Description" %>
<%= f.text_area :description %>
</div>
<div>
<%= f.label :movie, "Load a picture of the movie" %>
<%= f.text_field :remote_movie_url %>
<!--<%= f.file_field :movie %>-->
</div>
<div>
	<%= gotcha_error %>
	<%= gotcha %>
</div>
<div class="page-element">
	<%= f.submit "Submit", :disable_with => 'Submiting...' %>
</div>

<% end %>
</table>
</div>


app/views/movies/search_movies.html.erb
<%= render 'layouts/search' %>

app/views/movies/show.erb
<% if !@movie.movie_tagline.nil? %>
<%
  title @movie.name
%>
<% else %>
<%
  title @movie.name+':'+@movie.movie_tagline
%>
<% end %>
<div class="row-fluid">

<div class="span5">
<% cache("#{@movie.name}",:expires_in => 6.hours) do %>
<table>
  <tr>
      <td>
        <%= image_tag @movie.poster_url %>
    </td>
  </tr>
</table>  
</div>

<div class="span7">

<table class=" table table-bordered table-condensed table-striped">
  <caption><b>Listing Reviews for Movie</b></caption>
    <tr><td><b>Name:</b><%= @movie.name %></td></tr>
    <tr><td><b>Description: </b><%= @movie.movie_description %></td></tr>
  <tr><td><b>Tagline: </b><%= @movie.movie_tagline %></td></tr>
  <tr>
    <td>
        <b>Overall Movie rating: </b>
          <%= render_chart(@chart, 'chart') %>
          <div id='chart'></div>
    </td>
  </tr>
  <tr><td><b>Genres: </b><%= @movie.movie_genres %></td></tr>
  <tr><td><b>Release Date: </b><%= @movie.movie_au_release_date %></td></tr>
  <tr><td><b>Actors: </b><%= @movie.movie_cast %></td></tr>
  <tr><td><b>Production: </b><%= @movie.movie_production_companies %></td></tr>
  <tr><td><b>Runtime: </b><%= @movie.movie_runtime %> min</td></tr>
  <% if !@movie.trailer_url.empty? %>
  <tr><td><iframe width="290" height="200" src="<%= @movie.trailer_url %>" frameborder="0" allowfullscreen></iframe></td></tr>
  <% end %>
  </table>

<table class="table table-bordered table-condensed table-striped">
    <caption><b>Twitter Buzz</b></caption>
    <% movie_tweets(@movie.name,"popular").each do |tweet| %>
    <tr>
      <td>
        <b><%= tweet.user.name %>: </b><i><%= tweet.text %></i>
      </td>
    </tr>
    <% end %>
</table>

<% end %>
<% count = 0 %>
<% @reviews.each do |post| %>
<table class="table table-bordered table-condensed table-striped">
  <tr><td><%= @users[count].username %> rates it <b><%= post.rating %></b> and says</td></tr>
  <tr><td><i>"<%= post.review %>"</i></td></tr>
    <% if user_signed_in? %>
    <% if @users[count].email == current_user.email %>
      <tr><td>
        <div class="btn">
          <%= link_to "Edit", :controller => "reviews", :action => "edit", :id => post.id %>
        </div>
        <div class="btn">
          <%= link_to 'Delete', post, :confirm => 'Are you sure?',:method => :delete %>
        </div>      
    <% end %>
  <% end %>
   <% count = count + 1 %>
<% end %>
<tr>
  <td>
    <div class="btn">
      <%= link_to "Add your Review", :controller => "reviews", :action => "new",:movie => @movie.id  %>
    </div>
  </td>
</tr>
      <% if admin_signed_in? %>
  <tr>  
        <td><%= link_to 'Edit Movie', edit_movie_path(@movie),:class => "btn btn-inverse" %></td>
  </tr>
      <% end %>
</table>
</div>

</div>  

app/views/movies/suggest.html.erb
<%
   title 'Suggest: suggest me a movie'
%>

Enter the movie name you like to find similar movies
<%= form_tag( :controller => "movies", :action => "suggest") do %>
    <%= label_tag (:name) %>
    <%= text_field_tag :name %>
    <%= submit_tag "suggest",:class => "btn" %>
<% end %>
<% if !@suggest_results.nil? %>
<div class="span6">
  <table class="table table-bordered table-condensed table-striped">
    <caption><b>Movies similar to: <%= @name.capitalize %></b></caption>
    <% @suggest_results.each do |post| %>
    <tr>
      <td>
            <%= link_to "#{post['original_title']}",controller: "movies", action: "create_from_tmdb",id: post['id'] %>
      </td>
    </tr>
    <% end %>
  </table>
</div>
<% else %>
    <% if :name.empty? %>
        <b>Sorry.Did not find any movie suggestions matching your query</b>
    <% end %>
<% end %>

app/views/movies/upload.html.erb
<%
  title 'Upload: upload new list'
%>
<%= form_tag({action: :import}, multipart: true) do %>
  <%= file_field_tag 'file' %>
	<%= submit_tag "Save changes" %>
<% end %>
 