config/routes.rb
Ohmyroots::Application.routes.draw do

  resources :credits

  devise_for :admins
match 'faqs/privacy', :to => 'faqs#privacy'
  resources :faqs

  root to: "movies#dashboard"
  match 'movies/dashboard', :to => 'movies#dashboard'
  match 'movies/upload', :to => 'movies#upload'
  match 'reviews/show', :to => 'reviews#show'
  match 'movies/suggest', :to => 'movies#suggest'

  resources :reviews
  resources :movies
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  devise_for :users, :controllers => { :registrations => "registrations" }
  

  match 'show/:id', :to => 'movies#show'
  

   match ':controller(/:action(/:id))(.:format)'
end

app/models/credit.rb
class Credit < ActiveRecord::Base
  attr_accessible :credit
end

app/controllers/credits_controller.rb
class CreditsController < ApplicationController
  before_filter :authenticate_admin!, :only => [:new, :edit,:destroy], :except => [:index]
  # GET /credits
  # GET /credits.json
  def index
    @credits = Credit.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @credits }
    end
  end

  # GET /credits/1
  # GET /credits/1.json
  def show
    @credit = Credit.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @credit }
    end
  end

  # GET /credits/new
  # GET /credits/new.json
  def new
    @credit = Credit.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @credit }
    end
  end

  # GET /credits/1/edit
  def edit
    @credit = Credit.find(params[:id])
  end

  # POST /credits
  # POST /credits.json
  def create
    @credit = Credit.new(params[:credit])

    respond_to do |format|
      if @credit.save
        format.html { redirect_to @credit, notice: 'Credit was successfully created.' }
        format.json { render json: @credit, status: :created, location: @credit }
      else
        format.html { render action: "new" }
        format.json { render json: @credit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /credits/1
  # PUT /credits/1.json
  def update
    @credit = Credit.find(params[:id])

    respond_to do |format|
      if @credit.update_attributes(params[:credit])
        format.html { redirect_to @credit, notice: 'Credit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @credit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /credits/1
  # DELETE /credits/1.json
  def destroy
    @credit = Credit.find(params[:id])
    @credit.destroy

    respond_to do |format|
      format.html { redirect_to credits_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/credits_helper.rb
module CreditsHelper
end

app/views/credits/_form.html.erb
<%= form_for(@credit) do |f| %>
  <% if @credit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@credit.errors.count, "error") %> prohibited this credit from being saved:</h2>

      <ul>
      <% @credit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :credit %><br />
    <%= f.text_area :credit %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/credits/edit.html.erb
<h1>Editing credit</h1>

<%= render 'form' %>

<%= link_to 'Show', @credit %> |
<%= link_to 'Back', credits_path %>

app/views/credits/index.html.erb
<table>
  <tr>
    <th>Credits</th>
    <!--th></th>
    <th></th>
    <th></th-->
  </tr>

<% @credits.each do |credit| %>
  <tr>
    <td><%= credit.credit %></td>
    <!--td><%= link_to 'Show', credit %></td>
    <td><%= link_to 'Edit', edit_credit_path(credit) %></td>
    <td><%= link_to 'Destroy', credit, method: :delete, data: { confirm: 'Are you sure?' } %></td-->
  </tr>
<% end %>
</table>

<br />

<!--%= link_to 'New Credit', new_credit_path %-->

app/views/credits/new.html.erb
<h1>New credit</h1>

<%= render 'form' %>

<%= link_to 'Back', credits_path %>

app/views/credits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Credit:</b>
  <%= @credit.credit %>
</p>


<%= link_to 'Edit', edit_credit_path(@credit) %> |
<%= link_to 'Back', credits_path %>