config/routes.rb
Ohmyroots::Application.routes.draw do

  resources :credits

  devise_for :admins
match 'faqs/privacy', :to => 'faqs#privacy'
  resources :faqs

  root to: "movies#dashboard"
  match 'movies/dashboard', :to => 'movies#dashboard'
  match 'movies/upload', :to => 'movies#upload'
  match 'reviews/show', :to => 'reviews#show'
  match 'movies/suggest', :to => 'movies#suggest'

  resources :reviews
  resources :movies
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  devise_for :users, :controllers => { :registrations => "registrations" }
  

  match 'show/:id', :to => 'movies#show'
  

   match ':controller(/:action(/:id))(.:format)'
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= nav_bar :brand => image_tag("SmallLogo2_315X85.png"),:brand_link => root_path,:static => :top,:align => :center do %>
<%= nav_bar %>
    <%= menu_group do %>
        <%= menu_item "Home", root_path %>
		<%= menu_item "Search", movies_path %>

		<% if user_signed_in? %>
			
			<%= drop_down "Account" do %>
				<%= menu_item "My Reviews", reviews_show_path %>
				<%= menu_item "Edit Account", edit_user_registration_path %>
				<%= menu_item "Logout", destroy_user_session_path %>
			<% end %>
		<% else %>	
			<%= menu_item "Sign Up", new_user_registration_path %>
			<%= menu_item "Login", new_user_session_path %>
		<% end %>
		
        <%= drop_down "About" do %>
			<%= menu_item "FAQs", faqs_path %>
			<%= menu_item "Terms", faqs_privacy_path %>
			<%= menu_item "Privacy", faqs_privacy_path %>
			<%= menu_item "Credits", credits_path %>
		<% end %>
	<% end %>
<% end %>

app/views/layouts/_search.html.erb
<div>
<%= search_form_for @search do |f| %>
    <%= f.label :name_cont, "Search Movies" %>
    <%= f.text_field :name_cont,:class => "search-query" %>
    <%= f.submit "Search" %>
<% end %>

<% if !@movie_results.nil? %>
<table class="table table-striped">
  <tr>
    <th><%= sort_link @search,:name, "Name"  %></th>
  </tr>
  <% @movie_results.each do |post| %>
      <tr>
        <td><%= post.name %></td>
        <td><%= link_to 'Show', post %></td>
      </tr>
  <% end %>
</table>
</div>
<% end %>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--title><%= content_for?(:title) ? yield(:title) : "Movie Pulse" %></title-->
    <title>Movie Pulse: <%= yield :title %></title>
    <meta name="description"><%= yield :description %></meta>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <script type="text/javascript">  
        (document).ready(function () {  
            $('.dropdown-toggle').dropdown();
        });  
   </script>  
    <%= javascript_include_tag "application" %>
    <!--[if lt IE 9]>
    <script src="components/html5shiv/html5shiv.js"></script>
    <![endif]-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
    <%= analytics_init if Rails.env.production? %>
    <%= favicon_link_tag 'favicon.ico' %>
  <style type="text/css">
  .loader {
  position: fixed;
  left: 0px;
  top: 0px;
  width: 100%;
  height: 100%;
  z-index: 9999;
  background: url(<%= asset_path 'page-loader.gif' %>) 50% 50% no-repeat rgb(249,249,249);
}
  </style>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script type="text/javascript">
$(window).load(function() {
  $(".loader").fadeOut("slow");
})
$(form).load(function() {
  $(".loader").fadeIn("slow");
})
</script> 
<script src='https://www.google.com/jsapi'></script>   
  </head>
  <body>
  <div class="loader"></div>
    <!--header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header-->
    <!-- Part 1: Wrap all page content here -->
          <%= render 'layouts/navigation' %>

    <div id="wrap">
    <div id="main" role="main">
      <div class="container-fluid">
        <div class="content">
           <div class="row">
           <div class="span3"></div>
            <div class="span9">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
                        <!--div class="span3"-->
              <!--<%= google_adsense_include_tag client: 'ca-pub-2003857859925620', slot: '7152347448', width: '160', height: '600' %>
              <%= google_adsense_include_tag client: 'ca-pub-2003857859925620', slot: '2582547046', width: '300', height: '250' %>-->
            <!--/div-->

          </div>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </div>
  

  <!--div id="push"></div-->


    <!--div id="footer">
      <div class="container">
    <footer class="footer">
        <%= link_to "FAQ",controller: "/faqs",action: "index" %>
        <%= link_to "Terms", faqs_privacy_path %>
        <%= link_to "Privacy", faqs_privacy_path %>
        <%= link_to "Credits",controller: "/credits",action: "index" %>
        @2013 Movie Pulse
    </footer> 
      </div>
    </div-->
  </body>
</html>